pipeline {
    agent any
    stages {
        stage('Install Dependencies') {
            steps {
                bat 'cd C:\\Capgemini\\Notes_Automation_Framework\\automation && python -m pip install -r requirements.txt'
            }
        }
        stage('Run API Tests') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    bat 'cd C:\\Capgemini\\Notes_Automation_Framework\\automation && python -m pytest tests/api -n 2 --alluredir=allure-results -v'
                }
            }
        }
        stage('Run UI Tests') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    bat 'cd C:\\Capgemini\\Notes_Automation_Framework\\automation && python -m pytest tests/ui -n 2 --alluredir=allure-results -v'
                }
            }
        }
        stage('Run Hybrid E2E Tests') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    bat 'cd C:\\Capgemini\\Notes_Automation_Framework\\automation && python -m pytest tests/e2e --alluredir=allure-results -v'
                }
            }
        }
        stage('Generate Allure Report') {
            steps {
                allure(
                    includeProperties: false,
                    jdk: '',
                    results: [[path: 'C:\\Capgemini\\Notes_Automation_Framework\\automation\\allure-results']]
                )
            }
        }
    }
    post {
        always {
            archiveArtifacts(
                artifacts: 'C:\\Capgemini\\Notes_Automation_Framework\\automation\\screenshots\\*.png',
                allowEmptyArchive: true
            )
        }
        success {
            echo 'Pipeline executed successfully.'
        }
        unstable {
            echo 'Some test cases failed. Build marked as UNSTABLE.'
        }
        failure {
            echo 'Pipeline execution failed.'
        }
    }
}