[pytest]
addopts =
    -v
    --tb=short
    --alluredir=allure-results
    --reruns=2
    --reruns-delay=1

testpaths = tests

markers =
    ui:       UI Selenium tests
    api:      API automation tests
    e2e:      Hybrid End-to-End tests
    smoke:    Quick sanity checks
    negative: Negative/error path tests
    perf:     Performance validation

log_cli       = true
log_cli_level = INFO
log_format    = %(asctime)s [%(levelname)-8s] %(name)s — %(message)s
log_date_format = %H:%M:%S
